### ISSUE TITLE
OPTIONS call on tnrs/infer_context

### ISSUE THREAD

**Issue by mtholder** [OpenTreeOfLife/ws_wrapper#12]
tree.opentreeoflife.org/:1 Access to XMLHttpRequest at 'https://api.opentreeoflife.org/v3/tnrs/infer_context' from origin 'https://tree.opentreeoflife.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by bredelings** [comment]
If I run `curl -X OPTIONS https://api.opentreeoflife.org/v3/tnrs/infer_context -v` then I get some verbose output that includes:

```
< HTTP/1.1 200 OK
< Date: Tue, 30 May 2023 15:54:49 GMT
< Server: waitress
< Access-Control-Allow-Credentials: true
< Access-Control-Allow-Headers: content-type
< Access-Control-Allow-Methods: POST
< Access-Control-Allow-Origin: *
< Access-Control-Max-Age: 86400
< Content-Length: 0
< X-Powered-By: otc-tol-ws
```

ws_wrapper should be a transparent tunnel here, and `otc-tol-ws` is generating OPTIONS headers that seem fine.

The code in otcetera is in `ws/tolwsbooting.cpp` in function `options_headers()`.

**Comment by mtholder** [comment]
I think this was just a side effect of disk being full
